// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEMOTOR_H
#define DRIVEMOTOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Commands/StickOfJoy.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveMotor: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> leftMotor;
	std::shared_ptr<SpeedController> rightMotor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	DriveMotor();
	void InitDefaultCommand();
	void SetLeftMotor(double rate); //these are split, beacuse the methods that goes in the subsystem should be fairly multipurpose.
	void SetRightMotor(double rate);
	void StopLeftMotor();
	void StopRightMotor();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
