// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "../../../git/Training_Board/src/OI.h"

#include "SmartDashboard/SmartDashboard.h"

#include "../../../git/Training_Board/src/Commands/DriveForward.h"
#include "../../../git/Training_Board/src/Commands/DriveThenRotate.h"
#include "../../../git/Training_Board/src/Commands/TurnDistance.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick1.reset(new Joystick(0));
    
    b_Button.reset(new JoystickButton(joystick1.get(), 2));
    b_Button->WhileHeld(new TurnDistance());
    a_Button.reset(new JoystickButton(joystick1.get(), 1));
    a_Button->WhileHeld(new DriveForward(0.5));

    // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystick1() {
   return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
