// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../../../git/Training_Board/src/RobotMap.h"

#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveMotorSpeedController1;
std::shared_ptr<SpeedController> RobotMap::driveMotorSpeedController2;
std::shared_ptr<Encoder> RobotMap::encoderMotorQuadratureEncoder1;
std::shared_ptr<SpeedController> RobotMap::encoderMotorSpeedController1;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveMotorSpeedController1.reset(new Talon(0));
    lw->AddActuator("DriveMotor", "Speed Controller 1", std::static_pointer_cast<Talon>(driveMotorSpeedController1));
    
    driveMotorSpeedController2.reset(new Spark(1));
    lw->AddActuator("DriveMotor", "Speed Controller 2", std::static_pointer_cast<Spark>(driveMotorSpeedController2));
    
    encoderMotorQuadratureEncoder1.reset(new Encoder(0, 1, false, Encoder::k4X));
    lw->AddSensor("EncoderMotor", "Quadrature Encoder 1", encoderMotorQuadratureEncoder1);
    encoderMotorQuadratureEncoder1->SetDistancePerPulse(1.0);
    encoderMotorQuadratureEncoder1->SetPIDSourceType(PIDSourceType::kRate);
    encoderMotorSpeedController1.reset(new Spark(2));
    lw->AddActuator("EncoderMotor", "Speed Controller 1", std::static_pointer_cast<Spark>(encoderMotorSpeedController1));
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
